server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flightbookingdb?createDatabaseIfNotExist=true&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  jpa:
    database-platform: com.hibernate.dialect.MySQL8Dialect
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: https://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
