server:
port: 8080
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/flightbookingdb?createDatabaseIfNotExist=true&useUnicode=true
    username: root
  jackson:
    serialization:
      fail-on-empty-beans: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  mvc:
    format:
      date: yyyy-MM-dd
  
  eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: https://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


    
